### ISSUE TITLE
Add acknowledgments and helpText, remove comments, remove __pycache__ directory

### ISSUE THREAD

**Issue by jcfr** [fredericpanthier/SlicerKidneyStoneCalculator#1]
* `KidneyStoneCalculator.py`:
  * [x] Update contributor lists
  * [x] Add missing organization
  * [x] Update helpText
  * [x] Update acknowledgementText
  * [x] Remove commented code
  * [x] Fix formatting of dictionaries
    * Good:  `"foo": [1.2, 3, 4]`
    * Bar: `"foo":[1.2,3,4]`

**Comment by fredericpanthier** [comment]
Hello, all the changes have been made,
regards
